AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - bin/bundle
    - db/schema.rb
    - db/migrate/**
Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/AbcSize:
  Max: 19
Metrics/BlockLength:
  IgnoredMethods: [ 'describe', 'context' ]
Metrics/MethodLength:
  Max: 15
